version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.15
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  setup-ec2:
  executor: aws-clu/default
  steps:
    - checkout
    - run:
      name: Install terraform
      command: |
        sudo apt-get update
        sudo apt-get install -y gnupg software-properties-common curl

        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add - 
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

        sudo apt-get update && sudo apt-get install terraform
  - aws-cli/setup:
      profile-name: my-profile
  - run:
      name: Run terraform
      command: |
      cd terraform
      terraform init
      terraform validate
      terraform apply -auto-approve

workflows:
  build-and-deploy:
    jobs:
    - aws-ecr/build-and-push-image:
      repo: "${AWS_RESOURCE_NAME_PREFIX}"
      tag: "latest"
    - setup-ec2:
      requires:
        - aws-ecr/build-and-push-image